# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Food Coop Oldenburg
tagline:          ''
description:      'Wir kaufen bei ökologischen, regionalen Erzeuger*innen zu fairen Preisen gemeinschaftlich ein.'
url:              http://foodcool.de
baseurl:          /

author:
  name:           ''
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Tamriel/tamriel.github.io
